login/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from .views import DashboardLogin, DashboardLogout

urlpatterns = [
    re_path(r'^$', DashboardLogin.as_view()),
    re_path(r'^login', DashboardLogin.as_view()),
    re_path(r'^logout', DashboardLogout.as_view()),
]

may1stapi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from rest_framework import routers
#from users.views import UserList

#router = routers.DefaultRouter()
#router.register(r'list', UserList)


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('login.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^operations/', include('operation.urls')),
    re_path(r'^users/', include('users.urls')),
    re_path(r'^parameters/', include('parameter.urls')),
    re_path(r'^cotisations/', include('cotisation.urls')),
    re_path(r'^credits/', include('credit.urls')),
    re_path(r'^userprofiles/', include('userProfile.urls')),
    re_path(r'^user_credits/', include('userCredit.urls')),


    #path('', include(router.urls)),
]

userProfile/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from .views import UserProfilePage, UserProfileAPI

router = routers.DefaultRouter()
router.register(r'api', UserProfileAPI)

urlpatterns = [
    re_path(r'', include(router.urls)),
    re_path(r'^index/(?P<selected_user_id>[0-9]+)', UserProfilePage.as_view()),
]

userProfile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="user_userProfile", null=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2, blank=True, default=0)
    start_date = models.DateField(editable=True)
    created_at = models.DateTimeField(auto_now=True)

userProfile/views.py
from django.shortcuts import render

from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .serializers import UserProfileSerializer
from django.contrib.auth.models import User
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.renderers import JSONRenderer
from django.views import View
from .models import UserProfile


class UserProfilePage(View):
    template_name = 'dashboard/userprofiles/index.html'

    @method_decorator(login_required(login_url='/login'))
    def get(self, request, selected_user_id):
        return render(request, self.template_name, {'selected_user_id': selected_user_id})


class UserProfileAPI(viewsets.ModelViewSet):

    # renderer_classes = [JSONRenderer]

    queryset = UserProfile.objects.all().order_by('-created_at')
    serializer_class = UserProfileSerializer
    permission_classes = [permissions.IsAuthenticated]

    @action(detail=False, url_path="get_userprofile_by_userid/(?P<user_id>[0-9]+)")
    def get_userprofile_by_userid(self, request, user_id=None):

        user = User.objects.get(pk=user_id)
        userProfile = UserProfile.objects.filter(user=user).first()
        userProfileSer = UserProfileSerializer(userProfile)

        return Response(userProfileSer.data)

templates/dashboard/userprofiles/vue_components/form.html
 <div class="box">
  <div class="box-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="montant">Montant</label>
          <input type="number" class="form-control select2" style="width: 100%;" id="id_amount" name="amount" v-model="item.amount">
           <div style="color:red" v-if="error['amount']">
            [[ error['amount'] ]]
          </div>
        </div>
       
      </div>
      <!-- /.col -->
      <div class="col-md-6">
        
        <label>Date initiale</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          <input type="text" class="form-control pull-right" id="id_start_date" name="start_date" v-model.lazy="item.start_date" readonly>
          <div style="color:red" v-if="error['start_date']">
            [[ error['start_date'] ]]
          </div>
        </div>
        
        <!-- /.form-group -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <button type="button" class="btn bg-purple pull-right" v-on:click="updateItem(item.id)">Valider</button>
        <a href="/users/index" class="btn bg-default pull-left">Annuler</a>
    </div>

</div>
<!-- /.box -->

templates/dashboard/userprofiles/vue_components/form_userProfile.html
 <div class="box">
  <div class="box-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="montant">Montant</label>
          <input type="number" class="form-control select2" style="width: 100%;" id="id_amount" name="amount" v-model="item.amount">
           <div style="color:red" v-if="error['amount']">
            [[ error['amount'] ]]
          </div>
        </div>
       
      </div>
      <!-- /.col -->
      <div class="col-md-6">
        
        <label>Date initiale</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          <input type="text" class="form-control pull-right" id="id_start_date" name="start_date" v-model.lazy="item.start_date" readonly>
          <div style="color:red" v-if="error['start_date']">
            [[ error['start_date'] ]]
          </div>
        </div>
        
        <!-- /.form-group -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <button type="button" class="btn bg-purple pull-right" v-on:click="updateItem(item.id)">Valider</button>
        <a href="/users/index" class="btn bg-default pull-left">Annuler</a>
    </div>

</div>
<!-- /.box -->

templates/dashboard/userprofiles/vue_components/list.html
 <div class="box">
  <div class="box-body">

    <div class="table-responsive">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="row">
            <div class="col-sm-6">
              <h2><b>C</b>otisations</h2>
            </div>
            
          </div>
        </div>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <!-- <th>Nom & Prenom</th> -->
              <th>Date</th>
              <th>Montant</th>
              <th>Ajoute par</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(item,index) in items" :key="item.id" >
              <!-- <td>[[ item.last_name ]] [[ item.first_name ]]</td> -->
              <td>[[ item.date ]]</td>
              <template v-if="item.cotisation">
                <td>[[ item.cotisation.amount]]</td>
                <td>[[ item.cotisation.created_by.last_name]] [[ item.cotisation.created_by.first_name]]</td>
                <td>
                  <a href="javascript:void(0)" class="delete"><i class="fa fa-trash-o" data-toggle="tooltip" title="Delete" v-on:click="deleteItem(item.cotisation.id,index)"></i></a>
                </td>
              </template>
             <template v-else>
              <td>--</td>
              <td>--</td>
              <td>              
                 <a  href="javascript:void(0)"class="edit" ><i class="fa fa-plus" data-toggle="tooltip" title="Edit" v-on:click="createItem(index)"></i></a>
              </td>

            </template>
            </tr>
          </tbody>
        </table>
        <div class="clearfix">
          <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
          <ul class="pagination">
            <li class="page-item disabled"><a href="#">Previous</a></li>
            <li class="page-item"><a href="#" class="page-link">1</a></li>
            <li class="page-item"><a href="#" class="page-link">2</a></li>
            <li class="page-item active"><a href="#" class="page-link">3</a></li>
            <li class="page-item"><a href="#" class="page-link">4</a></li>
            <li class="page-item"><a href="#" class="page-link">5</a></li>
            <li class="page-item"><a href="#" class="page-link">Next</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>